### PR TITLE
Prep for 6.3.0 release

### PR DESCRIPTION
**Pull request by facelessuser**

### CODE REVIEW

**Comment by facelessuser** [comment]
@gir-bot lgtm

**Comment by AbhaysinghBhosale** [comment]
> _No description provided._

After this release builds of mkdocs in travis started failing from last hour.

**Comment by facelessuser** [comment]
I need an error. What were you seeing?

**Comment by ofek** [comment]
For reference: https://github.com/Python-Markdown/markdown/issues/905

**Comment by AbhaysinghBhosale** [comment]
It was failing due to versions of markdown and pymdown-extension. mkdocs-material was expecting different versions.

**Comment by facelessuser** [comment]
Yes, this has been recently fixed in mkdocs-material.

**Pull request merged**
