### PR TITLE
Snippets - changed "appending" to "prepending"

### PR DESCRIPTION
**Pull request by seanmadsen**

### CODE REVIEW

**Comment by facelessuser** [comment]
Good catch.

**Comment by facelessuser** [comment]
Could you add prepending to the dictionary so the spelling test passes?

**Comment by seanmadsen** [comment]
Now passing. Very cool that you have a spelling test! :ok_hand:

**Comment by facelessuser** [comment]
It is likely that prepend and some of the other forms are already in aspell's main dictionary.  I usually only add words that cause failure, but this is fine.  Thanks for the pull.  It doesn't matter how many times I read over the docs, I always miss something :).

**Pull request merged**
