### PR TITLE
fancylist inject class remove semicolon

### PR DESCRIPTION
**Pull request by joapuiib**
Removes the semicolon at the end of the injected class in `fancylists`.

### CODE REVIEW

**Comment by joapuiib** [comment]
Oh, I assumed it was a typo. I've never seen semicolons in HTML classes.

Isn't more common not to use them?

**Comment by facelessuser** [comment]
> Oh, I assumed it was a typo.

No, not a typo, but I honestly don't have strong feelings either way. It seemed like it was stated as a problem, but I don't think it really matters.

> Isn't more common not to use them?

It wouldn't surprise me if one was somewhat more popular than others. I know people that some have definite preference for or against them at the end.

I don't know what the split on preference is. I think at some point it used to be required, but I think these days most browsers are more forgiving. If you go online, you'll often see it taught to always add the `;` probably because it used to be needed, but yeah, I know there are people who don't add them and I've probably left them off at times myself. This is probably the most thought I've put into the significance of trailing commas in inline styles 🙃.

I guess my point is I don't really care it's there or not, but I guess I'm not against removing it either 🤷🏻.

**Comment by joapuiib** [comment]
> This is probably the most thought I've put into the significance of trailing semicolons in inline styles 🙃.

I'm talking about setting the element `class` attribute, not `style`.

With the current implementation, CSS selector should be `.fancylists-lower-alpha\;` instead of `.fancylists-lower-alpha`.

Example:

```css
.fancylists-lower-alpha\; li::marker {
    content: counter(list-item, lower-alpha) ") ";
}
.fancylists-upper-alpha\; li::marker {
    content: counter(list-item, upper-alpha) ") ";
}
```

**Comment by facelessuser** [comment]
Oh, a semicolon in the class?! Oh, that is definitely a typo.

**Comment by facelessuser** [comment]
I completely missed that

**Comment by facelessuser** [comment]
@gir-bot lgtm

**Comment by joapuiib** [comment]
Sorry for the misunderstanding. I should have written a better PR text.

Thanks!

**Comment by facelessuser** [comment]
I should have looked over the review closer 😅

**Comment by facelessuser** [comment]
Released: https://github.com/facelessuser/pymdown-extensions/releases/tag/10.10.1

**Pull request merged**
