### PR TITLE
Fixes for Pygments 2.12

### LINKED ISSUE #1665: pygments v2.12.0 breaks pymdownx.superfences
### Description

Since [pygments update today](https://github.com/pygments/pygments/blob/master/CHANGES), code fences are not correctly translated when using `pymdownx.superfences`, e.g.:
````markdown
```sh
code
```
````
is translated to:
```html
<code>sh code</code>
```
i.e. what should have been a `<pre>` tag with shell syntax highlighting has become a `<code>` tag with `sh` as plain text content.  Also without code highlighting, it becomes a `<code>` tag only. This was observed with MkDocs. Downgrading `pygments` to `<2.12` solves the issue.

I'm not sure whether this is an issue with `pymdown-extensions`, requiring an update or `pygments` introducing an unintended change/bug, but reporting it here did fit better since code fences, including `markdown.extensions.codehilite`, without `pymdownx.superfences` works well.

#### OOT

In this context I btw found interesting that with `pymdownx.superfences` enabled, `pymdownx.highlight` is used automatically even when only `markdown.extensions.codehilite` is enabled explicitly. Generally not an issue, I guess this is even necessary in our case to have code fences in `pymdownx.tabbed` correctly highlighted, but I just want to verify, so we can remove `markdown.extensions.codehilite` safely from our MkDocs config.

### Minimal Reproduction

Reproducing on Debian/APT based distros:
````sh
sudo apt install python3-distutils
curl -sSfO 'https://bootstrap.pypa.io/get-pip.py'
sudo python3 get-pip.py
rm get-pip.py
pip3 install mkdocs pymdown-extensions pygments
cat << '_EOF_' > mkdocs.yml
site_name: Test
markdown_extensions:
- pymdownx.superfences
_EOF_
mkdir docs
cat << '_EOF_' > docs/index.md
```sh
code
```
_EOF_
mkdocs build
grep code site/index.html
````

To resolve:
```sh
pip3 install 'pygments<2.12'
mkdocs build
grep code site/index.html
```

### Version(s) & System Info

- Operating System: Debian Bullseye and Bookworm
- Python Version: 3.9.2 and 3.10.4
- Package Version:
    ```
    Markdown==3.3.6
    mkdocs==1.3.0
    Pygments==2.12.0
    pymdown-extensions==9.3
    ```

### PR DESCRIPTION
**Pull request by facelessuser**
Resolves #1665

### CODE REVIEW

**Comment by facelessuser** [comment]
@gir-bot lgtm

**Comment by Lucas-C** [comment]
Hi!

It appears that this PR solves the issue I had, reported here: https://github.com/pygments/pygments/issues/2119

Thank you!

I see you've just made a new release, but it seems that the package hasn't been published on Pypi: https://pypi.org/project/pymdown-extensions/#history

**Comment by facelessuser** [comment]
Sorry, new build backend. I need to fix it. It'll be just a bit.

**Comment by facelessuser** [comment]
It's there now. I switched the build backend and forgot to update the deploy action. Wasn't expecting to rush a release today 🙃

**Comment by Lucas-C** [comment]
Thanks for fixing it quickly 😊

**Pull request merged**
