### PR TITLE
Replace MaxCDN, which has shut down

### PR DESCRIPTION
**Pull request by samdobson**
Twemoji is currently broken, due to MaxCDN shutting down. This may only be a short-term fix.

See https://github.com/twitter/twemoji/issues/580

### CODE REVIEW

**Comment by facelessuser** [comment]
I do imagine this will break some tests.

**Comment by samdobson** [comment]
My bad. I think this should do it.

**Comment by facelessuser** [comment]
I imagine from the root directory you will have to run `python3 run_tests.py -u`.

**Comment by samdobson** [comment]
Thanks for the pointer. Tests are now passing locally. I force-pushed to clean up the mess.

**Comment by facelessuser** [comment]
Can you install Pygments locally and re-run `run_tests.py -u`? We run with Pygments installed.

**Comment by samdobson** [comment]
No worries, that's done. Not too sure what has made codecov unhappy.

**Comment by facelessuser** [comment]
Codecov isn't unhappy. Recently, there is a lag for things to get updated their, or sometimes certain tests don't get updated at all. It's kind of annoying.

**Pull request merged**
