### PR TITLE
Correction to raphael.js URL

### PR DESCRIPTION
**Pull request by davidhrbac**
The web site lives on www.raphaeljs.com only.

### CODE REVIEW

**Comment by facelessuser** [comment]
Yeah, modern browsers strip that out and they also take links without them.  So it doesn't surprise me that my copy paste from chrome removed the `www`.  But yeah, having the `www` is canonical.

Thanks.

**Comment by facelessuser** [comment]
Just curious, but did the link not work?  I only ask because all my links are missing the `www`.

**Comment by davidhrbac** [comment]
I don't know. I can see no www.raphaeljs.com record.

```bash
‹hrb33-toshiba› 19:21 $ dig raphaeljs.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> raphaeljs.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27054
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;raphaeljs.com.			IN	A

;; AUTHORITY SECTION:
raphaeljs.com.		60	IN	SOA	ns1.p13.dynect.net. domains.sencha.com. 3 3600 600 604800 60

;; Query time: 60 msec
;; SERVER: 10.5.16.11#53(10.5.16.11)
;; WHEN: Thu Jan 26 19:21:43 CET 2017
;; MSG SIZE  rcvd: 111

✔ ~/Dokumenty/dev/github/pymdown-extensions [raphael_url {origin/raphael_url}|✔] 
‹hrb33-toshiba› 19:21 $ dig www.raphaeljs.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.raphaeljs.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1567
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.raphaeljs.com.		IN	A

;; ANSWER SECTION:
www.raphaeljs.com.	125	IN	A	54.173.116.232

;; AUTHORITY SECTION:
raphaeljs.com.		72790	IN	NS	ns1.p13.dynect.net.
raphaeljs.com.		72790	IN	NS	ns2.p13.dynect.net.
raphaeljs.com.		72790	IN	NS	ns3.p13.dynect.net.
raphaeljs.com.		72790	IN	NS	ns4.p13.dynect.net.

;; ADDITIONAL SECTION:
ns3.p13.dynect.net.	13179	IN	A	208.78.71.13
ns1.p13.dynect.net.	13179	IN	A	208.78.70.13
ns4.p13.dynect.net.	13179	IN	A	204.13.251.13
ns2.p13.dynect.net.	13179	IN	A	204.13.250.13

;; Query time: 37 msec
;; SERVER: 10.5.16.11#53(10.5.16.11)
;; WHEN: Thu Jan 26 19:21:47 CET 2017
;; MSG SIZE  rcvd: 212
```

**Comment by facelessuser** [comment]
The site has moved, that's why: http://dmitrybaranovskiy.github.io/raphael/.

If you can update it to that, I think we're good.

**Comment by facelessuser** [comment]
Thanks! Probably wouldn't have got that for a while.

**Pull request merged**
