### PR TITLE
Support PathLike objects in base_path

### PR DESCRIPTION
**Pull request by oprypin**
This enables this usage in MkDocs (note that specifying as a list already works):

```yml
  - pymdownx.snippets:
      base_path: !relative $docs_dir
```

Currently you get an error:
```
               self.base_path = [os.path.abspath(b) for b in base]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           TypeError: 'DocsDirPlaceholder' object is not iterable
```

### CODE REVIEW

**Comment by facelessuser** [comment]
We would need tests to confirm that things are working with PathLike objects.

**Comment by facelessuser** [comment]
Can you enable `check_paths` to make sure that portion works as well?

**Comment by facelessuser** [comment]
Hmm, it may not be necessary to enable `check_paths`. I looked over the code again and it seems we test the file's existence whether it is enabled or not, `check_paths` just raises an error if the file is not found. Since the test demonstrates the inserted content is there, we can assume it is checking and finding things as needed.

**Comment by oprypin** [comment]
So does anything need to be changed? I understood this as probably not?

**Comment by facelessuser** [comment]
No, I think it is fine, thanks for checking back in.

**Comment by facelessuser** [comment]
@gir-bot lgtm

**Pull request merged**
